### ISSUE TITLE
Adding a side drawer

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#101]
Can I please add a sidebar that will have the name of the app, logo, and an 'About' section that will explain what this app is about. It can also have the username so that the user can quickly find out with which account he or she has logged in. I believe that in the future there will be more things as well that we could display in this sidebar. 

The sidebar can be added to the left of the search bar.

**Comment by anotherwebguy** [comment]
Can i work on this issue under gssoc plz assign me this issue

**Comment by EAsmithaShrree** [comment]
Hello, I was under the assumption that the contributor who creates an issue will automatically be given first priority for resolving the issue as well. Is that not how it works? I am interested in working on this issue, hence please assign it to me.

**Comment by anotherwebguy** [comment]
> Hello, I was under the assumption that the contributor who creates an issue will automatically be given first priority for resolving the issue as well. Is that not how it works? I am interested in working on this issue, hence please assign it to me.

sorry , yeah sure u must be assigned it first i'am here to help if u need

**Comment by infiniteoverflow** [comment]
I am sorry , this issue will be assigned to @EAsmithaShrree . sorry for the late response , i was caught up with some personal issues.

@EAsmithaShrree You can get started with this.
@anotherwebguy Feel free to raise new issues for any new ideas u have.

**Comment by infiniteoverflow** [comment]
@EAsmithaShrree If you could add a About Page with description of the app and an appropriate illustration from undraw.com, i can give u a label 3 for the PR.

**Comment by anotherwebguy** [comment]
Hey @infiniteoverflow plz.let me know if there's anything else left to design

**Comment by infiniteoverflow** [comment]
Sure @anotherwebguy , we will have enough work. We will update u soon on the same

**Comment by EAsmithaShrree** [comment]
> @EAsmithaShrree If you could add a About Page with description of the app and an appropriate illustration from undraw.com, i can give u a label 3 for the PR.

Yes I can do this work.

**Comment by anotherwebguy** [comment]
Can i work on this issue now since it's been 16 days and i've already shown you the ui how would i design this side drawer plz assign me this issue 
@infiniteoverflow
