### ISSUE TITLE
Grammatical error in the Readme file 

### ISSUE THREAD

**Issue by anirudhsai20** [infiniteoverflow/Libro#105]
There is a small grammatical error in the Readme file that needs corretion.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by infiniteoverflow** [comment]
I am sorry , i cant assign an issue for grammatical changes. It is against the norms of OpenSource Contribution. Feel free to look for some other documentation updates or even for code changes/bugs.
