### ISSUE TITLE
Share a Book Via Other Apps

### ISSUE THREAD

**Issue by SamarpanCoder2002** [infiniteoverflow/Libro#106]
**Is your feature request related to a problem? Please describe.**
If anyone want to share books via link through social media, this feature till not added....

**Describe the solution you'd like**
A menu icon, with every book information, gives access to share the book link through social media....

**Describe alternatives you've considered**
Mentioned Above

**Additional context**
I am also a GSSOC21 participant...If I can forward with that..please assign me to here.......
Thanks @infiniteoverflow

**Comment by infiniteoverflow** [comment]
@SamarpanCoder2002 , this will be helpful only when we add a real book. For now we are adding dummy data.

We will get back to u once we work on this.
