### ISSUE TITLE
Adding Chat Screen

### ISSUE THREAD

**Issue by anotherwebguy** [infiniteoverflow/Libro#108]
**Is your feature request related to a problem? Please describe.**
I would like to design the chat screen ui for the app, plz let me work on this issue @infiniteoverflow

**Comment by anotherwebguy** [comment]
Plz assign me this issue @Souvikns @infiniteoverflow @adityathakurxd @pratyushmp

**Comment by infiniteoverflow** [comment]
@anotherwebguy you can get started with this. Just build a chat screen and later we will integrate firebase and other logics.

for testing purpose you can do something like this : The first message that is entered will be shown on the right (user message) , and the second message that is submitted can be shown on the left (reply message) and so on.

**Comment by infiniteoverflow** [comment]
And also add an emoji picker too , which can be inserted along with the text message

**Comment by anotherwebguy** [comment]
Okay i'll do it
