### ISSUE TITLE
Develop HomePage Widget

### ISSUE THREAD

**Issue by Praneeth-rdy** [infiniteoverflow/Libro#11]
I hope we should also design a homepage for the application. Can you please review this issue and assign it to me?

**Comment by infiniteoverflow** [comment]
Yes , currently we dont have a design. Try to build a basic one for now , later we can modify it accordingly.
Dont start with the PR for now , i will let u know some details within the next 2 days.

**Comment by Praneeth-rdy** [comment]
Hey @Sahil-kachhap,
As the exact work(design) isn't confirmed yet, I cannot assure you anything for now regarding this. If I feel that I cannot alone do it in the required time, then I will definitely take your help and we can divide the work. But for now, I am assuming that I can solve this issue by myself. I will definitely reach out to you in case of difficulty.
Thank you for your interest 😊.

**Comment by infiniteoverflow** [comment]
@Sahil-kachhap , @Praneeth-rdy will add a tentative ui for now, later if any enhancements are required we can discuss in our project channel and u guys can work on it together.

**Comment by rohats871** [comment]
Hey, I would like to say if possible we can create our own designs and come up with a joint discussion of what to add from each different design, making it faster for all of us

**Comment by infiniteoverflow** [comment]
Sure @rohats871 , i was planning to do that. But before that we need a tentative ui to consider as a benchmark. So once @Praneeth-rdy adds the screen we can try for more improvisation.

**Comment by infiniteoverflow** [comment]
We have the discussion channel open for brainstorming. @Praneeth-rdy , @rohats871 , @Sahil-kachhap You guys can share your ideas there and we will come to a conclusion.

And @Praneeth-rdy Kindly share your current approach to the UI of the homepage. Share if you have any designs.

**Comment by Praneeth-rdy** [comment]
Where is this discussion channel? Is there any slack or discord server for the same?

I am having the following design in my mind. I hope this can give us a potential start.

![IMG_20210310_192406](https://user-images.githubusercontent.com/57290210/110640295-abc91a80-81d6-11eb-8198-4bdc073ffc4a.jpg)

**Comment by Sahil-kachhap** [comment]
> Where is this discussion channel? Is there any slack or discord server for the same?
> 
> I am having the following design in my mind. I hope this can give us a potential start.
> 
> ![IMG_20210310_192406](https://user-images.githubusercontent.com/57290210/110640295-abc91a80-81d6-11eb-8198-4bdc073ffc4a.jpg)

@Praneeth-rdy Checkout the tabs above Issues, Pull Request and next comes Discussion go over there .

Get over there we will discuss on the homepage design over there. Do post this design over there

**Comment by infiniteoverflow** [comment]
Lets discuss this in the HomePage Design Discussion.

**Comment by infiniteoverflow** [comment]
@Praneeth-rdy update on this ?

**Comment by Praneeth-rdy** [comment]
@infiniteoverflow Sorry, I was a bit busy the last one/two days. The UI development part is completed but while integrating the code with the current project and running it, I am getting an error saying **google-services.json file is missing**. When I checked the gitignore of the repo, this file is added in it. Can you help me out in proceeding further or in generating this file?

**Comment by infiniteoverflow** [comment]
You can find the link to the file in the project README.md

**Comment by Praneeth-rdy** [comment]
Yes, found it. Also, The app stays on the login screen itself even after successful login. I am replacing the homescreen in Homescreen.dart with the UI which I made.

**Comment by infiniteoverflow** [comment]
yes, go ahead.
