### ISSUE TITLE
Sign up Page validation : when passwords don't match

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#114]
On the signup page, no error is thrown when the content in fields 'Password' and 'Confirm Password' don't match. The user is allowed to signup to the app even if different inputs are given in both fields. 

I would like to add the necessary validation to avoid this. 

![image](https://user-images.githubusercontent.com/74728570/116277412-1217f580-a7a3-11eb-84fe-10c24cbae3db.png)

**Comment by infiniteoverflow** [comment]
Sure @EAsmithaShrree , you can get started with this.

**Comment by EAsmithaShrree** [comment]
Hey, so I noticed that validators have been written for all TextFormFields but _signUpFormKey.currentState.validate() hasn't been called. But FirebaseCrashlytics catches most of the errors and shows an alert box for each. As of now, I have added a condition to check both passwords and show an alert box if they don't match (when the signup button is clicked). 

However, if you want I can just call the validate method instead. 

Personally, I feel that we can remove all validators and show alert boxes instead. Please tell me what you would like me to do!

**Comment by infiniteoverflow** [comment]
@EAsmithaShrree Try using snackbars to show errors...showing an alertbox wont have a good user experience

Using FirebaseCrashlytics wont be an ideal way to validate the fields... can u do it manually using .validate(). And u need to check for one more condition ie, password == confirmPassword

You can add a manual check for the same once the normal validate() is run , if they are not same you can show a snackbar , or else u can go ahead with the sign up part...

**Comment by infiniteoverflow** [comment]
@EAsmithaShrree Is this issue fixed ?

**Comment by EAsmithaShrree** [comment]
Not yet, I wanted to resolve my doubts because I wasn't extremely sure
about what you wanted. Will work on it now.
