### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#115]
We need to create a Contact Us Page , that can give a brief overview of the app , and then at the end show the list of our amazing contributors.

You can use the same code used in our README.md file to show the Contributors list. You just need to figure how to render a Markdown file in dart code.

**Comment by SapinderSingh** [comment]
@infiniteoverflow I can work on this issue, as a participant of GSSOC 21

**Comment by infiniteoverflow** [comment]
Sure , go ahead.

**Comment by SapinderSingh** [comment]
@infiniteoverflow The best way to fetch the contributors is from GitHub API. 

Using this url - api.github.com/repos/infiniteoverflow/libro/contributors, 

However, they allow only few unauthenticated requests. Kindly, configure GitHub api for this project.

**Comment by infiniteoverflow** [comment]
Yeah , i will configure the api for this project. Meanwhile u can work on with url itself... i believe it will let u run enough requests for now for building the ui...

And this api requires that u create a Model class and a separate util file for running the api request. Should i create those for u , or will u create it ?

**Comment by SapinderSingh** [comment]
@infiniteoverflow I will create those files.
