### ISSUE TITLE
Adding a 'LOG OUT' option

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#117]
Shall I add a 'Log out' functionality for users to log out of the app when they want to? 

I was thinking that I could add this option in the side drawer and in the Profile Screen.

**Comment by infiniteoverflow** [comment]
Yes you can go ahead with this. First try to finish the earlier issue that u are working on, then u can start with this.

**Comment by EAsmithaShrree** [comment]
Yes sure. Will finish that one first and then move on to this.

**Comment by infiniteoverflow** [comment]
Sure...
