### ISSUE TITLE
Checking if user is already logged in

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#119]
Heyy I would like to check if the user is already logged in and if he is, then I want to ensure that he doesn't have to enter his credentials and log in again. Only if he logs out, he will have to enter his email and password and log in. Kindly let me work on this issue!

**Comment by infiniteoverflow** [comment]
This feature has already been integrated @EAsmithaShrree . So i may have to close this issue. But feel free to create new issues for creative ideas !!

**Comment by EAsmithaShrree** [comment]
But it asks me to enter my credentials and log in each time I want to use the app. Is it a problem with my code then? But I used upstream to keep my code updated!
