### ISSUE TITLE
Book description page

### ISSUE THREAD

**Issue by anotherwebguy** [infiniteoverflow/Libro#122]
I would like to design the book description page under gssoc. Plz assign me this issue @infiniteoverflow

**Comment by infiniteoverflow** [comment]
Sure , create a screen that takes in an image link to the book cover , and the name of the book as a parameter and display those details on the screen for now. Later we will think of adding descriptions and all.

**Comment by anotherwebguy** [comment]
> Sure , create a screen that takes in an image link to the book cover , and the name of the book as a parameter and display those details on the screen for now. Later we will think of adding descriptions and all.

Sure i'll make the ui as such so that it can be also be used for description in future if wanted
