### ISSUE TITLE
Profile screen enhancement

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#128]
I just noticed that in the Profile Page we are displaying an image. Will it be the image that the user uploads? If yes, then I would like to try out working on getting the image for the profile picture and updating it. I was thinking that if the user doesn't upload an image, then we could just add the first two letters of the user's name as we did in Main Drawer.

**Comment by infiniteoverflow** [comment]
Yes , u can for now go ahead and add the first two letters of the name as the icon. Later once we setup the database , u can fetch the image from Firebase.

**Comment by infiniteoverflow** [comment]
Hii @EAsmithaShrree  , any update on this.

**Comment by EAsmithaShrree** [comment]
Will be done by this weekend. Sorry held up with assessments.

**Comment by infiniteoverflow** [comment]
Sure sure !!

**Comment by Ayushi7456** [comment]
I would like to work as a GSSoC participant. May i create new issue for splash page UI enhancement?

**Comment by EAsmithaShrree** [comment]
Hello @infiniteoverflow , sorry for not finishing this issue for this long. I will finish this by tonight
