### ISSUE TITLE
Text on the button not getting displayed completely in the Intro Screen[BUG]

### ISSUE THREAD

**Issue by madhuvanthi27** [infiniteoverflow/Libro#129]
**Describe the bug**
It appeared as "CONTIN" instead of "CONTINUE" on the button in the opening page (intro_screen) on my phone. Some letters on the button go missing.

**To Reproduce**
1. When a user opens the app for the first time, the intro screen appears. 
2. When a user logs out, they are redirected to the intro screen.

**Expected behavior**
It should appear as "CONTINUE" but it appears as "CONTI" on the button on my phone. 

**Screenshots**
![front_page](https://user-images.githubusercontent.com/68513622/118088690-0e13e680-b3e5-11eb-8abb-72eee4d7e1d0.jpeg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4
 - Android Version: 7.0 NRD90M
 - MIUI Version: MIUI Global 11.0.2

**Additional context**
I feel that this problem is because of the minFontSize mentioned in the AutoSizeText widget. So either the minFontSize can be removed or "CONTINUE" can be changed to something short and simple like "GO".

**Comment by madhuvanthi27** [comment]
I would like to work on this issue as part of GSSOC'21.

**Comment by infiniteoverflow** [comment]
Sorry for the late reply @madhuvanthi27  , You can go ahead and fix this.

**Comment by madhuvanthi27** [comment]
Sure. No problem. Should I change "continue" to "GO" or just fix "continue"?
