### ISSUE TITLE
Profile screen enhancement - maintaining list of books

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#135]
In the Profile Screen, apart from Personal data, Favourites and Bookmarks, can I add another card for maintaining a list of books that the user has read. We could either get this info from the database or the user could manually enter it but the concept behind this feature is that it will make our app the 'One stop for everything about books' since the user will be able to come to our app to check the list of books they have read so that they don't accidentally borrow the same books again.

**Comment by infiniteoverflow** [comment]
Sure , you can go ahead with this.
