### ISSUE TITLE
Wrong Error Message when Email already exists in DB

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#140]
During Sign-up, if an email is already registered in the Database, then the error should be "Email already exists, please Log-in using that."

![Screenshot 2021-10-05 at 10 27 11 AM](https://user-images.githubusercontent.com/40236624/135962590-08fdbe9d-1ed1-43b4-8db6-f680aa793910.png)

**Comment by shyamss097** [comment]
Can I take this up?

**Comment by infiniteoverflow** [comment]
Sure @shyamss097 . Go ahead !
