### ISSUE TITLE
Creating templates for Issues and Pull Requests

### ISSUE THREAD

**Issue by Praneeth-rdy** [infiniteoverflow/Libro#15]
I think having pre-defined templates for the Issues and PRs will help us in maintaining uniformity while creating an issue or PR. I want to add these as default templates to the repo. Can you please assign this to me?

**Comment by Sahil-kachhap** [comment]
@Praneeth-rdy I have sent a PR on Contributing guidelines. If that gets merged, you can add your templates over there. So that, everything would be in one place.

**Comment by infiniteoverflow** [comment]
@Praneeth-rdy i believe u have a issue already assigned to you. I will share the details for that soon. Once thats merged , you can start with this.

**Comment by Praneeth-rdy** [comment]
> @Praneeth-rdy I have sent a PR on Contributing guidelines. If that gets merged, you can add your templates over there. So that, everything would be in one place.

My idea was to add the templates to the .github directory. So that when people create an Issue or PR, then GitHub will automatically provide them with these templates by default.

**Comment by Praneeth-rdy** [comment]
> @Praneeth-rdy i believe u have a issue already assigned to you. I will share the details for that soon. Once thats merged , you can start with this.

Sure.

**Comment by Souvikns** [comment]
@Praneeth-rdy as all other participants were opening issues, so as to help them we created the issue template, so you are still working on this issue please focus on the PR template.

**Comment by Praneeth-rdy** [comment]
Sure @Souvikns.
I was working on another issue of the same project and created a PR as a part of it. So, I will resolve this issue immediately after my PR is merged.
