### ISSUE TITLE
Integrate to firebase

### ISSUE THREAD

**Issue by nicks101** [infiniteoverflow/Libro#16]
- Creating a new firebase project and add the project to the firebase console.   
- Adding configuration files to ios and android folders.  

Since it'll require a firebase (email) account, let me know how to proceed with this issue.

**Comment by anotherwebguy** [comment]
> * Creating a new firebase project and add the project to the firebase console.
> * Adding configuration files to ios and android folders.
> 
> Since it'll require a firebase (email) account, let me know how to proceed with this issue.

Can i work on this issue,plz assign me this as a part of gssoc'21
here's my email ,add me on console
mohitrajputms123@gmail.com

**Comment by infiniteoverflow** [comment]
@nicks101 I will create an account and add you as collaborator. Kindly share your email id.

**Comment by infiniteoverflow** [comment]
@anotherwebguy I am sorry , but since this issue is authored by a participant , i may have to assign it to her. You can look forward to more issues.

**Comment by infiniteoverflow** [comment]
@nicks101 Your task would be to integrate the ios with firebase. Android would be done by participants who are working on Social Logins.

**Comment by nicks101** [comment]
> @nicks101 Your task would be to integrate ios with firebase. Android would be done by participants who are working on Social Logins.

okay

**Comment by nicks101** [comment]
> @nicks101 I will create an account and add you as collaborator. Kindly share your email id. You can DM me you email.

done
