### ISSUE TITLE
Email and Password(User's choice) Authentication With Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [infiniteoverflow/Libro#17]
I would like to integrate this app with email and password(User's choice) authentication with firebase.   I also worked on this in one of my projects.....I noticed that the Google Authentication issue already present there... But sometimes there exist a feature like that(With Email and Manual Password)...... Can I go forward with that? And If @infiniteoverflow gives permission to that, please assign me to that project........I am also a **_gssoc21_** participant..... Thank you @infiniteoverflow

**Comment by infiniteoverflow** [comment]
Sure , that sounds good. Kindly share your email id. And you can start with the work once i tell you. Because there are other integrations going on parallely , so don't want to create any merge conflicts for u.

**Comment by SamarpanCoder2002** [comment]
> Sure , that sounds good. Kindly share your email id. And you can start with the work once i tell you. Because there are other integrations going on parallely , so don't want to create any merge conflicts for u.

Yeah sure.....my Gmail: samarpanofficial2021@gmail.com

After your permission, I will surely start working on that project...thanks for assigning me to that

**Comment by infiniteoverflow** [comment]
I have added you as a collaborator. You can start working on that by the end of the day today.

**Comment by infiniteoverflow** [comment]
@SamarpanCoder2002 You can get started with it. Download the Google services json file from the console and integrate the email-pass authentication.
There are two screens , try to implement both SignUp and Login.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 You can get started with it. Download the Google services json file from the console and integrate the email-pass authentication.
> There are two screens , try to implement both SignUp and Login.

Ok I start work from today.... Thanks for the permission

**Comment by infiniteoverflow** [comment]
No problem and Good Luck.

**Comment by SamarpanCoder2002** [comment]
> No problem and Good Luck.

I will add email and password authentication surely but can I store the data in cloud firestore or not???

**Comment by infiniteoverflow** [comment]
No , for now dont do that. Just print the UID once the user is authenticated successfully.

**Comment by SamarpanCoder2002** [comment]
> No , for now dont do that. Just print the UID once the user is authenticated successfully.

Ok I will complete signup and login with email verification....If user verify registered email and then log in, Then I only print the UID....is that okay????

**Comment by SamarpanCoder2002** [comment]
Pull Request Send(https://github.com/infiniteoverflow/Libro/pull/28#issue-590788511)... Please merge it. If there any problem....you can freely tell me......Thanks
