### ISSUE TITLE
Intro Screen

### ISSUE THREAD

**Issue by rohats871** [infiniteoverflow/Libro#20]
<img width="387" alt="Screenshot 2021-03-10 at 1 02 42 PM" src="https://user-images.githubusercontent.com/68010359/110592921-e87a1f00-81a0-11eb-9bce-fa7d1578fdae.png">
The Intro screen is not according to the screen size for iPhone 11 pro & 12 Pro Max

**Comment by infiniteoverflow** [comment]
Oh yes, would you like to fix that ?

**Comment by Vrushti24** [comment]
cAN I TRY THIS @infiniteoverflow ?

**Comment by infiniteoverflow** [comment]
@Vrushti24 You may have to wait for his reply before I can assign. If it's just a bug report, you can work on it. Else if he is interested in working on this issue, I may have to assign him this issue.

**Comment by Vrushti24** [comment]
Okayy I understand that 👍

**Comment by rohats871** [comment]
yes i would like to fix the issue

**Comment by rohats871** [comment]
and i am also looking for other iOS devices

**Comment by infiniteoverflow** [comment]
Okay sure, go ahead. Just set the width based on the screen width , and try using AutoSizeText if necessary for the text inside the Button.

**Comment by infiniteoverflow** [comment]
@Vrushti24 We will have more issues coming up soon. Do look out for them.

**Comment by rohats871** [comment]
cant upload it , i've already tried multiple times , says error 403

**Comment by rohats871** [comment]
@Souvikns  help me a little here

**Comment by Souvikns** [comment]
yeah, what is the problem, what are you trying to upload?

**Comment by rohats871** [comment]
> yeah, what is the problem, what are you trying to upload?

upload the changes , its just wont let me

**Comment by Souvikns** [comment]
yeah, actually you have to fork this repo first

**Comment by rohats871** [comment]
> yeah, actually you have to fork this repo first

can we talk somewhere else in dm's if possible?

**Comment by Souvikns** [comment]
then make a PR from your branch to this branch.

**Comment by Souvikns** [comment]
> > yeah, actually you have to fork this repo first
> 
> can we talk somewhere else in dm's if possible?

In GSSOC discord, but I guess participants cant message yet

**Comment by rohats871** [comment]
> then make a PR from your branch to this branch.

okay after this

**Comment by Souvikns** [comment]
once you fork you make a copy of this repo that is under your username, namely `rohats871/libro` then clone this repo (your forked version) make any changes that you like, then commit,push. then make a PR. TO make a PR just open the  github page of your forked repo there you will find the option to make a PR.

**Comment by rohats871** [comment]
<img width="1228" alt="Screenshot 2021-03-12 at 2 05 01 PM" src="https://user-images.githubusercontent.com/68010359/110914114-f31ceb80-833b-11eb-8ef5-56af287149c2.png">


@Souvikns  still the same

**Comment by Souvikns** [comment]
you are trying to push to the original repo, where you don't have any rights. If you have forked it clone the forked version.

**Comment by Souvikns** [comment]
If you still have an issue you can check out this https://www.youtube.com/watch?v=nT8KGYVurIU
