### ISSUE TITLE
Models for the app

### ISSUE THREAD

**Issue by nicks101** [infiniteoverflow/Libro#21]
Models at this point could be :
 
- user
- book

 I would suggest using [freezed package](https://pub.dev/packages/freezed) or we can make them by scratch.

Basic functions for model

- toMap (convert to map)
- fromMap (return instance of model/class from map)
- from snapshot (return instance of model/class from [firebase document snapshot](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot))
- toString (override)

**Comment by infiniteoverflow** [comment]
This sounds like a good idea. But we are currently working on deciding the Post-authentication features and after that, we will let u know about the models we can build. So let this issue be open, and within some days we will get started with a concise plan.

**Comment by infiniteoverflow** [comment]
@nicks101 Closing this for now , will add individual issues for each model and let you know about it soon.

**Comment by nicks101** [comment]
> @nicks101 Closing this for now , will add individual issues for each model and let you know about it soon.

Yeah, better idea.
