### ISSUE TITLE
Discussion Group : Open

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#24]
On the top tabbar of this repo , you can find a Tab : `Discussions` , we can use that to discuss any specific ideas that you have or brainstorm in ongoing discussions.

**Comment by rohats871** [comment]
So while trying multiple ways on fixing the bug for iOS , I found out the bar looks much better when circular rather then starting from bottom as we have in tentative design. It looks better as i feel it goes with the circular theme or login and sign up page too
<img width="319" alt="Screenshot 2021-03-10 at 9 40 14 PM" src="https://user-images.githubusercontent.com/68010359/110660291-695d0900-81e9-11eb-850a-e29d28a2d64c.png">

**Comment by infiniteoverflow** [comment]
@rohats871 We can go with the existing one for now , later we will look for any better improvisations.
And try to comment on your issue. It will be easier to understand.
