### ISSUE TITLE
Design Mockup

### ISSUE THREAD

**Issue by Souvikns** [infiniteoverflow/Libro#25]
To access the mockup file https://www.figma.com/file/YFnbf7wm8mxGuAGmujRNDo/Libro?node-id=0%3A1

**Comment by Samdid** [comment]
@infiniteoverflow @Souvikns  can you explain this issue in detail?

**Comment by Souvikns** [comment]
@Samdid checkout #23 discussion.

**Comment by Samdid** [comment]
Okay
