### ISSUE TITLE
State Management with Provider

### ISSUE THREAD

**Issue by D-Ajay-Kumar** [infiniteoverflow/Libro#27]
# Feature

Adding Provider package for authentication and state management and drafting models for the app to make integration with the UI easy.

# Description

Introducing Provider package and creating provider classes for providing data like books list and user's data across all the screens of the app. The PR would include new models required for the app and provider classes for the same for authentication and providing the data across all screens without hassle.

## Models and Providers would include -
Book Model
Books List Provider 
User Model
Auth Provider

# Need

Creating models now before creating the whole UI would help know what widgets need to be used to show what data and would help in making the authentication. The provider classes with change notifier would be used to provide data to respective screens and knowing this before creating the UI would help improve the accuracy of mockups.

If the issue gets approved I would love to work on it. I am also a participant in GSSOC'21.

**Comment by infiniteoverflow** [comment]
I am sorry @D-Ajay-Kumar , we had planned on using the BLoC Architecture as that would be easier to work on for the beginners.
We will have issues coming up soon. Do look out for them.

I may have to close down this issue now. Feel free to create an issue for any ideas you may have for the app. Thanks.
