### ISSUE TITLE
Login Screen and Sign up Screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#3]
We would like to add a login and a sign up screen to be shown to users. The user should be able to toggle between the two. The illustrations that are used here is added in the assets folder.

The colors and fonts to be used is also added in the file `constants.dart` and fonts folder.

<img width="543" alt="Screenshot 2021-03-03 at 11 02 27 AM" src="https://user-images.githubusercontent.com/40236624/109757513-f31c3d80-7c0f-11eb-82cf-809ea89b831d.png">

**Comment by Neha62-lit** [comment]
I want to contribute in this project. @infiniteoverflow can this issue kindly assigned to me for GSSOC'21?

**Comment by infiniteoverflow** [comment]
Sure , you will be assigned this issue once the coding project starts.

**Comment by ajay963** [comment]
I am interested in contributing to this project but I am not participating in GSSOC can I contribute to this project ??

**Comment by infiniteoverflow** [comment]
I am sorry @ajay963 , i can assign only a single participant at a time. But dont worry we will have enough issues coming up soon , you can look forward to that.

**Comment by Saransh-cpp** [comment]
Please let me know if I can work on this issue or if there are any other issues I can work on as a part of GSSOC. Thanks!

**Comment by infiniteoverflow** [comment]
@Saransh-cpp Since this issue has been assigned to someone else on a First Come First Serve basis , i am afraid this issue cant be assigned to you. But yes, we will have tons of issues coming up soon , you can definitely work on those.

**Comment by infiniteoverflow** [comment]
@Neha62-lit You can start with this.
