### ISSUE TITLE
Setup HiveDB

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#32]
**Is your feature request related to a problem? Please describe.**
We need to setup a local storage for our device so that certain functionalities can fetch data offline.

**Describe the solution you'd like**
For this purpose we would like to implement HiveDB in our app for local storage.

After initializing Hive , the participants have to create a first time flag using which a user that opens the app for the first time should see the Introduction screen , or else if he is not a first timer , redirect him to the Authentication screen.

If any doubts , comment below or reach out to me or any of the mentors.

**Comment by D-Ajay-Kumar** [comment]
Never worked with adding Hive to Flutter but I can try doing it? Shall I?

**Comment by rohats871** [comment]
> Never worked with adding Hive to Flutter but I can try doing it? Shall I?

yess same , i would also like to know a lil more about it

**Comment by D-Ajay-Kumar** [comment]
I have started working on it, hopefully I'll be able to set up Hive successfully :)

**Comment by Souvikns** [comment]
Basically, we are using Hivedb instead of using shared preferences, we will be storing theme, settings, user preferences, etc. 
To know more about Hivedb do check out its docs https://docs.hivedb.dev/#/

**Comment by D-Ajay-Kumar** [comment]
Yes, I understand the use of the DB and have started working on integrating it to the app :)

**Comment by Souvikns** [comment]
Then I am assigning you this issue.

**Comment by D-Ajay-Kumar** [comment]
Thanks. Working on it.

**Comment by D-Ajay-Kumar** [comment]
I cannot test run the app locally because the google services file is missing. How do you propose I check whether the code is running fine or not?

**Comment by Souvikns** [comment]
wait on this, about the google services file I have to ask @infiniteoverflow.

**Comment by infiniteoverflow** [comment]
I will add the google drive link where i have added the file. I can add it to the repo , because GitGuardian bot will raise an issue.

**Comment by D-Ajay-Kumar** [comment]
Right right

**Comment by infiniteoverflow** [comment]
https://drive.google.com/file/d/1xLvwVTZQ3EWYl1uBna2IPp46hsjBQ8ul/view?usp=sharing

Here you go.

**Comment by D-Ajay-Kumar** [comment]
Also, the screens files are named as home_screen, login_screen etc. and even the home  screen widget is named HomeScreen while the widget in login_screen.dart is named LoginPage which breaks the consistency. Is it alright if I change the name to LoginScreen instead of LoginPage?

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
