### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [infiniteoverflow/Libro#37]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by infiniteoverflow** [comment]
You can work on this once you complete the earlier issue. And can you please specify what you are planning to use for this. ?

**Comment by rohank2502** [comment]
Ok i will be using the same concept as I apply on my git repository
https://github.com/rohank2502/Learn-GITHUB please have a look !!

**Comment by infiniteoverflow** [comment]
OK , looks good

**Comment by infiniteoverflow** [comment]
@rohank2502 You can start with this.
