### ISSUE TITLE
Add Introduction Screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#4]
Add a introduction screen to be shown to the user.

<img width="239" alt="Screenshot 2021-03-03 at 11 11 29 AM" src="https://user-images.githubusercontent.com/40236624/109758198-35924a00-7c11-11eb-9fd0-75721c2dab6e.png">

**Comment by ShrutiJ-01** [comment]
I would like to  work on this issue!

**Comment by Samdid** [comment]
@infiniteoverflow  I am a flutter developer. As I am a  GSSOC21' participant I want to contribute in this project so please assign this to me

**Comment by infiniteoverflow** [comment]
I will assign once the coding period starts.

@ShrutiJ-01 since u have commented on issue #6 , this issue will be assigned to @Samdid . But dont worry you will have plenty of issues to look out for during the 3 months !!

**Comment by infiniteoverflow** [comment]
@Samdid You can start with this.

**Comment by Samdid** [comment]
Okk

**Comment by mohitsoni-dev** [comment]
I can work on this issue simultaneously with @Samdid? You can select the best one out of our work. Thanks.

**Comment by Saransh-cpp** [comment]
> I can work on this issue simultaneously with @Samdid? You can select the best one out of our work. Thanks.

Don't make open source contributions a competition:), you can help the assigned person but don't compete for the same issue, I hope you understand.

**Comment by infiniteoverflow** [comment]
@mohitsoni-dev We cant have a single issue assigned to multiple participants. And dont worry i will add more issues within 2 days. So u can easily choose the one you are interested in.

**Comment by mohitsoni-dev** [comment]
> @mohitsoni-dev We cant have a single issue assigned to multiple participants. And dont worry i will add more issues within 2 days. So u can easily choose the one you are interested in.

Understood. Thanks.
