### ISSUE TITLE
Add SplashScreen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#40]
**Describe the solution you'd like**
We need to add a splash screen to the app which will be shown everytime the user restarts the app.

**Describe alternatives you've considered**
You can use any existing packages from pub.dev or implement your own logic.

Just use an existing image from the assets folder for the Screen and add the text "Libro" so that it looks aesthetic. For any help feel free reach out to the mentors or the PA.

**Comment by infiniteoverflow** [comment]
Interested Participants can comment on this issue if they want to work on this.

**Comment by Samdid** [comment]
@infiniteoverflow I would like to work on this issue, please assign it to me

**Comment by infiniteoverflow** [comment]
Sure , go ahead. Assigning you...

**Comment by infiniteoverflow** [comment]
Update on this @Samdid ?

**Comment by Samdid** [comment]
> Update on this @Samdid ?

About to complete, will make PR soon

**Comment by infiniteoverflow** [comment]
Okk sure.

**Comment by Samdid** [comment]
@infiniteoverflow  I am getting so many errors like this, what should I do?
![Libro_error](https://user-images.githubusercontent.com/70087884/111119380-13dd7f00-8590-11eb-8521-f2412728a2d6.png)

**Comment by infiniteoverflow** [comment]
Just set your SDK version in pubspec.yaml to sdk: ">=2.7.0 <3.0.0"

**Comment by adityathakurxd** [comment]
The dependencies listed have unsound null safety. Although I checked both `flutter_switch` and `auto_size_text` have pre-releases available with null safety. 

You can try upgrading to those. Or, to run mixed-version programs,
Disable sound null safety using the `--no-sound-null-safety flag` to the flutter command:
```
flutter run --no-sound-null-safety
```

**Comment by namancoder** [comment]
Can i work on this issue?

**Comment by infiniteoverflow** [comment]
@Samdid Are you working on this ?

**Comment by infiniteoverflow** [comment]
@namancoder As this issue is already assigned to a participant , we cant assign you this one now.

**Comment by Samdid** [comment]
> @Samdid Are you working on this ?

Yes

**Comment by infiniteoverflow** [comment]
@Samdid Can you please make a PR for the same as soon as possible. An issue cant be assigned to a particular participant for more than 7 days.

If you are facing any issues , do reach out to me.

**Comment by Samdid** [comment]
@infiniteoverflow actually, I was having an issue in my PC so I had reset my PC so now I have to reinstall and setup my all the IDEs so it is taking some time. I already mentioned this in the discussion section yesterday but I will make PR soon

**Comment by infiniteoverflow** [comment]
Okk , i missed your message in the discussion.

Sure, fix your PC properly and get started...try to finish it within 2 days. If not do let me know.

**Comment by Samdid** [comment]
> Okk , i missed your message in the discussion.
> 
> Sure, fix your PC properly and get started...try to finish it within 2 days. If not do let me know.

Sure👍 thanks

**Comment by infiniteoverflow** [comment]
@namancoder Would you like to work on this issue? Unfortunately Samdid wont be able to work on this.

**Comment by namancoder** [comment]
On it

**Comment by Shreya20-10** [comment]
I would like to work on this issue!!

**Comment by namancoder** [comment]
@infiniteoverflow  i am having little trouble in understading the code base and thus putting the splash screen file in order, can someone please help me in it?

**Comment by adityathakurxd** [comment]
> I would like to work on this issue!!
@Shreya20-10  As this issue is already assigned to a participant, we cant assign you this one now.
