### ISSUE TITLE
Screen to Gather User Details

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#46]
<img width="291" alt="Screenshot 2021-03-14 at 5 52 05 AM" src="https://user-images.githubusercontent.com/40236624/111053398-6aac6100-8489-11eb-92b9-e47106969481.png">

We need to develop a screen as per the design above. Feel free to modify accordingly. Skip the image picking part , leave a Placeholder in the image section.

Follow the color schemes defined in the file `constants.dart`.

And on clicking the `submit` button just print the input values in the console. Once we decide on the Firebase Database option, we will store those values there.

**Comment by D-Ajay-Kumar** [comment]
Can take it up

**Comment by infiniteoverflow** [comment]
Sure , go ahead. Assigning you.

**Comment by D-Ajay-Kumar** [comment]
Thanks. On it.

**Comment by D-Ajay-Kumar** [comment]
Does this seem okay? I've tried to keep the design as close to other forms in the app as possible to maintain the consistency.

![WhatsApp Image 2021-03-14 at 3 00 08 PM](https://user-images.githubusercontent.com/56850266/111063674-0bc10900-84d6-11eb-9206-f23e253a96a7.jpeg)

**Comment by infiniteoverflow** [comment]
@D-Ajay-Kumar Kindly add the Profile icon inside the Circle and as you can see in the image that i had shared , theres a small plus button inside a circle towards the bottom of this circle. Kindly add that too.

**Comment by D-Ajay-Kumar** [comment]
How about this? Used stack and positioned to place the small circle over there.

![WhatsApp Image 2021-03-14 at 5 43 03 PM](https://user-images.githubusercontent.com/56850266/111068025-f5727780-84ec-11eb-87dc-8a0d7406f1d4.jpeg)

**Comment by infiniteoverflow** [comment]
Looks amazing !!

**Comment by D-Ajay-Kumar** [comment]
And the address field should have a max length of 5 only?

**Comment by infiniteoverflow** [comment]
Yes , i was about to mention that. Let the max length be 5 lines for now , if it goes beyond it will be scrollable.

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
