### ISSUE TITLE
Add Email Verification Screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#48]
<img width="512" alt="Screenshot 2021-03-14 at 6 33 52 AM" src="https://user-images.githubusercontent.com/40236624/111054048-3fc50b80-848f-11eb-9781-71d072ae2644.png">

When a user authenticates using Email and password , check whether the user has verified their email. If not , then redirect them to the first screen , and make sure that a verification email is sent. If the user clicks "Continue" without verifying , then show a snackbar saying "You haven't Verified your email yet" , else show the AlertDialog as given in the second frame.

When the user clicks "Continue" in the alert dialog , redirect the user to the HomePage Screen.

**Comment by SapinderSingh** [comment]
@infiniteoverflow I want to work on this issue as a participant of GSSOC 21.

**Comment by Souvikns** [comment]
@SapinderSingh go ahead I am assigning you this issue.

**Comment by SapinderSingh** [comment]
@Souvikns @infiniteoverflow Please provide me the image which is used in the screenshot.

**Comment by infiniteoverflow** [comment]
Yes , i will update the repo with the assets soon

**Comment by infiniteoverflow** [comment]
@SapinderSingh You can get started with the work.
