### ISSUE TITLE
onGenerateRoutes Routes

### ISSUE THREAD

**Issue by nicks101** [infiniteoverflow/Libro#49]
## feature request related to a problem.
As the project is growing, it'll be difficult to maintain without a route system.

## Solution
Create a routes file `(onGenerateRoute)` and use routes defined in those for navigation.   

[Example](https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments#alternatively-extract-the-arguments-using-ongeneratero) of using onGenerateRoute.

Basic structure:
```
import 'package:flutter/material.dart';
Route<dynamic> generateRoute(RouteSettings settings) {
  // Here we'll handle all the routing

  switch (settings.name) {
      case 'login':
        return MaterialPageRoute(builder: (context) => LoginView())
}
```

Handle unknown routes:
```
switch (settings.name) {
  ...
  default:
    return MaterialPageRoute(builder: (context) => UndefinedView(name: settings.name,));
}
```
 Reference:
- [code snippets](https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c)

## Alternative

We can also use [auto_route](https://pub.dev/packages/auto_route/versions/1.0.0-beta.10) package.
It'll generate the routes for us, we'll just have to provide parameters. It is customizable.
`Warning`:  It's not migrated to null-safety yet.

**Comment by infiniteoverflow** [comment]
@nicks101 go ahead. Try to use the first approach , since auto_route is not migrated yet , it might cause an error when we ourselves migrate to a null-safe version.
