### ISSUE TITLE
Add Google Auth

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#5]
We have to implement Google Auth using Firebase.

**Comment by Manzee1609** [comment]
I would like to work on this issue
(I have experience in using Google Auth using Firebase in my prev Flutter projects)

**Comment by infiniteoverflow** [comment]
Thats great . I will assign as soon as the coding period starts.

**Comment by vinc3nati** [comment]
I'm also interested in adding this feature :)

**Comment by infiniteoverflow** [comment]
I am sorry @vinc3nati , i can assign this issue to only one participant at a time and thats based on First Come First Serve basis.

But, on the bright side you can look forward to more issues and you can contribute to those.

**Comment by infiniteoverflow** [comment]
@Manzee1609 You can get started with this.

**Comment by infiniteoverflow** [comment]
@Manzee1609 You can start the work. Kindly DM me your email , so that i can add you as collaborator the Firebase Project.

**Comment by Manzee1609** [comment]
Email- ***@***.***

**Comment by infiniteoverflow** [comment]
@Manzee1609 your email is filtered. I am not able to see it. It would be better if you can share it with me via Discord.

**Comment by Manzee1609** [comment]
email - mansikalaria16@gmail.com

**Comment by infiniteoverflow** [comment]
Any update on this @Manzee1609 ?

**Comment by Manzee1609** [comment]
The code is almost ready, will make pr tommorow.

**Comment by infiniteoverflow** [comment]
Sure.
