### ISSUE TITLE
GoogleService-Info.plist Missing [BUG]

### ISSUE THREAD

**Issue by rohats871** [infiniteoverflow/Libro#50]
**Describe the bug**
GoogleService-Info.plist is missing which is not letting me work on the app for iOS devices

<img width="1181" alt="Screenshot 2021-03-14 at 3 37 02 PM" src="https://user-images.githubusercontent.com/68010359/111064636-20ec6680-84db-11eb-8281-7b0b68f528aa.png">

**Comment by infiniteoverflow** [comment]
Thanks @rohats871 for mentioning this error. This will be fixed soon.

**Comment by rohats871** [comment]
> Thanks @rohats871 for mentioning this error. This will be fixed soon.

hey @infiniteoverflow i wanted to work along this project but due to this i wont be even open it , i hope we can resolve this soon :)

**Comment by infiniteoverflow** [comment]
Yes , this will be resolved soon. Meanwhile you can run the app in Android , it works fine there.

**Comment by infiniteoverflow** [comment]
@rohats871 Updated the link in the README

**Comment by rohats871** [comment]
> @rohats871 Updated the link in the README

works perfectly fine now thnx :)

**Comment by infiniteoverflow** [comment]
No problem
