### ISSUE TITLE
RenderFlex Error in Email Verification screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#54]
The following Bug has been spotted on Pixel 2XL Phones and other phones whose height is less that the same.

<img width="427" alt="Screenshot 2021-03-14 at 10 57 33 PM" src="https://user-images.githubusercontent.com/40236624/111078936-d3ddb400-851d-11eb-88fa-336ed1706bad.png">

Use an expanded widget to set the widget height and make all the widgets fit in the entire screen.

**Comment by amanxnanda** [comment]
Hey @infiniteoverflow  I would like to work on this issue. Thanks

**Comment by amanxnanda** [comment]
I created a PR for the same

**Comment by infiniteoverflow** [comment]
Okay sure. @amanxnanda Next time kindly wait for any of the mentors or me to assign you the issue and then you can get started with the PR.

**Comment by amanxnanda** [comment]
I am still new to open source but I will keep this in mind. Thanks.
