### ISSUE TITLE
Enable firebase crashlytics

### ISSUE THREAD

**Issue by nicks101** [infiniteoverflow/Libro#55]
1. Enable crashlytics for project (android and ios app).
2. Send report if and when any crash happens.
3. Send logs in every try catch, specifically the error and stack trace.

**Comment by infiniteoverflow** [comment]
I will check with Firebase crashlytics and get back to you on this. Because we don't want to overdecorate the app with all these at this initial stage.

**Comment by nicks101** [comment]
> I will check with Firebase crashlytics and get back to you on this. Because we don't want to overdecorate the app with all these at this initial stage.
> 

Yeah, sure. Let me know.

**Comment by infiniteoverflow** [comment]
@nicks101 You can get started with it.
Just let me if know if you will be able to integrate the iOS app too, if not I will do it from my side.

**Comment by nicks101** [comment]
> @nicks101 You can get started with it.
> Just let me if know if you will be able to integrate the iOS app too, if not I will do it from my side.

Okay, will let you know.

**Comment by nicks101** [comment]
> @nicks101 You can get started with it.
> Just let me if know if you will be able to integrate the iOS app too, if not I will do it from my side.

I couldn't integrate for iOS. It needs Runner (Xcode)
