### ISSUE TITLE
[Feature] Adding Linting Rules

### ISSUE THREAD

**Issue by amanxnanda** [infiniteoverflow/Libro#57]
Adding linting rules would really help in future code reviews as it acts as a pre-code review.
I will also make the code more readable throughout the project.

Lint package from pub.dev

**Comment by infiniteoverflow** [comment]
We already had an issue for Lint #9 , and it was added successfully. Apparently, i had to take it down due to some reasons. I will add those at a later stage.

Thank you for raising an issue for the same.
