### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [infiniteoverflow/Libro#59]
I would like to add code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by infiniteoverflow** [comment]
Sure @muthuannamalai12  , go ahead.
