### ISSUE TITLE
Add Facebook Auth

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#6]
We need to add Facebook Authentication to the app. API keys will be provided.

**Comment by ShrutiJ-01** [comment]
I would like to work on this issue if assigned under GSSOC 21

**Comment by infiniteoverflow** [comment]
Sure , this issue will be assigned to u once the coding period starts.

**Comment by infiniteoverflow** [comment]
@ShrutiJ-01 You can get started with this.

**Comment by infiniteoverflow** [comment]
@ShrutiJ-01 Kindly DM me your email id , so that i can add you as collaborator to the Firebase Project.

**Comment by ShrutiJ-01** [comment]
I've have sent it via discord and linkedin 👍

**Comment by infiniteoverflow** [comment]
Any update on this @ShrutiJ-01 ?

**Comment by ShrutiJ-01** [comment]
Started with it, will make a PR soon enough

**Comment by infiniteoverflow** [comment]
Okk sure.
