### ISSUE TITLE
Not Showing the login success popup when the user returns from the Home screen

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#64]
I believe that it will be a better user experience if the 'Congrats! Log-in...' popup is not displayed every time the user presses the back button from the Home Screen. 

The popup should only appear when he is actually logging into the app and not when he is returning from the homescreen.

![image](https://user-images.githubusercontent.com/74728570/111205025-c3483f00-85ec-11eb-9041-ee99706535e7.png)

**Comment by infiniteoverflow** [comment]
Yes , we will have to override the back button in the HomePage so that when the user presses back he will be prompted to "Press back again" to exit the app rather than going back to the login page.

**Comment by EAsmithaShrree** [comment]
Can I go ahead and try working on it or are we leaving it for later?

**Comment by infiniteoverflow** [comment]
Work on this once the other issue is solved. And comment here once you start with this.

**Comment by infiniteoverflow** [comment]
@EAsmithaShrree Something similar has been already done by some participant. Sorry about that , we will add some more new issues soon and u can work on those.
