### ISSUE TITLE
Adding a cross button in the login and signup message popups to enhance user experience

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#65]
I would like to add a cross button on the top right corner of the popups or a 'Dismiss' button so that it's clearer to the user that they can click on it to close the popups. 

![image](https://user-images.githubusercontent.com/74728570/111205996-dc9dbb00-85ed-11eb-919b-8acbba4e3e87.png)

**Comment by infiniteoverflow** [comment]
Yes , we need to add a Close button on the top. Would you like to work on it ?

**Comment by EAsmithaShrree** [comment]
Yes, I would like to do it!! I am a GSSOC'21 participant by the wayy

**Comment by infiniteoverflow** [comment]
You can start with this , once this is done , i wil assign you the other issue.

**Comment by infiniteoverflow** [comment]
@EAsmithaShrree Any updates on this ?

**Comment by EAsmithaShrree** [comment]
Almost done with this
