### ISSUE TITLE
Changing the app name from "book_donation" to Libro and changing the logo of the app.

### ISSUE THREAD

**Issue by GayatriMunde** [infiniteoverflow/Libro#66]
The name Libro sounds unique and good. Using it for the actual app is really a great idea.
Also I feel like instead of using flutter logo, using a well designed logo will be good.

![image](https://user-images.githubusercontent.com/69967336/111223722-8c315800-8603-11eb-861e-0d4ff9c46192.png)

**Comment by infiniteoverflow** [comment]
Yes , we need to change the logo and the app name. Would you like to work on this issue ?

**Comment by GayatriMunde** [comment]
Yes I would like to work on this issue.
