### ISSUE TITLE
[BUG]Firebase Crashlytics for IOS

### ISSUE THREAD

**Issue by Souvikns** [infiniteoverflow/Libro#69]
**Describe the bug**
The app is not running in IOS as firebase crashlytics is not set up for IOS

**Comment by Souvikns** [comment]
@rohats871 I am assigning this issue to you

**Comment by Souvikns** [comment]
@rohats871 @infiniteoverflow has already worked on this, and he will be pushing the code shortly

**Comment by rohats871** [comment]
> @rohats871 @infiniteoverflow has already worked on this, and he will be pushing the code shortly

oh okay thats a good news plus i will also love to know what he did

**Comment by infiniteoverflow** [comment]
@rohats871 I have updated the repo to support Firebase Crashlytics on iOS. Do have a look and feel free to reach out to use in case you have any doubts.
