### ISSUE TITLE
Adding Stripe (or any other payment method) for books

### ISSUE THREAD

**Issue by vinc3nati** [infiniteoverflow/Libro#7]
Each book can have different prices and say we keep a sale on book's prices we can update the cost dynamically using stripe as it is more popular and highly functional.

**Comment by infiniteoverflow** [comment]
Actually we are not planning to integrate payments in our app. We are acting as a portal to connect the people, later they can chat and meet in person and exchange or sell/buy books.

So , Sorry i may have to close this issue. But feel free to reach out to me on LinkedIn or the discord channel once the coding period starts if u have any other innovative ideas. We are always open to suggestions.
