### ISSUE TITLE
UserDetails Screen : Image Picker

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#70]
We need to fix the following bug with the InfoScreen :

<img width="387" alt="Screenshot 2021-03-17 at 9 04 33 AM" src="https://user-images.githubusercontent.com/40236624/111411522-b7e63800-8700-11eb-89d3-a665453e2962.png">

The Circular Image should be resized a bit lesser than it is now, and position the blue "+" icon towards the bottom of the CircleAvatar on its border.

**Comment by Neha62-lit** [comment]
@infiniteoverflow I would like to work on this issue!!

**Comment by infiniteoverflow** [comment]
Sure go ahead !!

**Comment by D-Ajay-Kumar** [comment]
Is there any way to permanently fix the relative position of two widgets? Like these 2 circles here.
