### ISSUE TITLE
Add Spinner in Login_Screen

### ISSUE THREAD

**Issue by rakshitkamboj** [infiniteoverflow/Libro#72]
**Problem**
After clicking login button for a while it looks like the app is stuck till the home_screen appears. To show the progress to the user I would like to add a spinner that will indicate the progress to the user.

**Solution**
I will be using modal_progress_hud library for that.

**Comment by infiniteoverflow** [comment]
@rakshitkamboj Since this package shows an overlay progress bar, is there any option to cancel the "Loading" in case an error is returned from the server.
For eg : We will be running the loader while waiting for the response from Firebase. In case, the network is lost while fetching data, then i believe the Loader will run in an infinite loop.

**Comment by rakshitkamboj** [comment]
@infiniteoverflow Okay I got your point.
To avoid that I will be using a boolean. In case, the network is lost then it will simply turn to false and the network Error will be shown.

**Comment by infiniteoverflow** [comment]
@rakshitkamboj In that case you may have to use Booleans for all perceived errors , but there are some errors that we cant anticipate also...

for that i would suggest , using a snackbar to show the loading , and it also has a timer right , if the time gets over u can specify what msg has to be shown...

**Comment by rakshitkamboj** [comment]
@infiniteoverflow Okay.
So you meant that I should use snackbar when clicked on login button and it will show a message in it "Loading" till it switches to Home screen and if the time limit extends then it will a error message.
Right?

**Comment by infiniteoverflow** [comment]
yes , correct.

A Snackbar with "Logging you in..." with a CircularProgressIndicator at the end. And if it timesout , show an error message like "Login Failed , try again later"

**Comment by rakshitkamboj** [comment]
Thanks @infiniteoverflow for assigning it to me .
I will try my best .

**Comment by infiniteoverflow** [comment]
Sure. Feel free to reach out to me in case you have any doubts.
