### ISSUE TITLE
Create profile page

### ISSUE THREAD

**Issue by amanxnanda** [infiniteoverflow/Libro#73]
**Is your feature request related to a problem? Please describe.**
Right now Libro doesn't have any profile page for the user.

**Describe the solution you'd like**
I would like to make a profile page if given the design.

**Comment by infiniteoverflow** [comment]
@Souvikns Can you share the Profile Screen UI if its ready.

**Comment by Souvikns** [comment]
![Profile Page](https://user-images.githubusercontent.com/41781438/111728610-3a066600-8893-11eb-89c7-f1ba8cff534d.png)

> @amanxnanda  feel free to experiment with different color schemes.

**Comment by amanxnanda** [comment]
Hey, @Souvikns  can you please provide me the color values. Thanks

**Comment by amanxnanda** [comment]
@infiniteoverflow @Souvikns can you please give me your feedback
<img src = "https://user-images.githubusercontent.com/34944818/111941992-5e16b100-8af8-11eb-9ddc-9efffc57d8cb.png" height = "500">

**Comment by Souvikns** [comment]
#f7f5fb
#f4f1fa
#002253
#e9e2f4
#9575cd

**Comment by Souvikns** [comment]
> 
> 
> @infiniteoverflow @Souvikns can you please give me your feedback
> <img alt="" height="500" src="https://user-images.githubusercontent.com/34944818/111941992-5e16b100-8af8-11eb-9ddc-9efffc57d8cb.png">

try to make the users image a little bit big and reduce the size of the name, so that the first focus would be the image rather than the text.

**Comment by amanxnanda** [comment]
How does it look now?
<img src = "https://user-images.githubusercontent.com/34944818/111962330-31729180-8b18-11eb-81f5-9e0c5318ec55.png" height = "500">

**Comment by infiniteoverflow** [comment]
Looks good to me. @Souvikns ?

**Comment by amanxnanda** [comment]
Okay, then I'll just create a PR.

**Comment by amanxnanda** [comment]
@infiniteoverflow I have a question, why IntelliSense is not working for this project?

**Comment by Souvikns** [comment]
@amanxnanda we need to close this issue soon, so we are giving you 2 days' time after that we will assign this issue to someone else.

**Comment by anotherwebguy** [comment]
Can i work on this issue plz assign me this issue
@infiniteoverflow @Souvikns

**Comment by infiniteoverflow** [comment]
Sure go ahead @anotherwebguy

**Comment by anotherwebguy** [comment]
why does intellisense doesn't work for this project ? @infiniteoverflow

**Comment by anotherwebguy** [comment]
hey @infiniteoverflow 
is this good?
![image](https://user-images.githubusercontent.com/66346161/114656663-1c9aaf80-9d0c-11eb-83f5-389754c0704d.png)

should i  make a pr now?

**Comment by anotherwebguy** [comment]
Hello sir plz reply should i make a pr? @infiniteoverflow @Souvikns

**Comment by infiniteoverflow** [comment]
Looks wonderful @anotherwebguy , go ahead and make a PR

**Comment by anotherwebguy** [comment]
> Looks wonderful @anotherwebguy , go ahead and make a PR

Ok thanks @infiniteoverflow
