### ISSUE TITLE
[Feature] Add Notification Screen

### ISSUE THREAD

**Issue by amanxnanda** [infiniteoverflow/Libro#74]
**Is your feature request related to a problem? Please describe.**
Adding a notifications page where users can view all the push notifications.

**Describe the solution you'd like**
We can try to implement the listview where each tile can be slided to dismiss the notification just like Gmail.

**Describe alternatives you've considered**
Or we can try some other approach given the design.

**Comment by infiniteoverflow** [comment]
Yes , we can plan for the same approach using a package : slidable

But implementing the Notification will take some time. It has many other works that have to be completed. So we will be working on this issue in the next phase of GSSOC.

For now, i will be closing this issue, but the team will notify u once we get started with the work.

**Comment by amanxnanda** [comment]
@infiniteoverflow okay
