### ISSUE TITLE
Package Issue in pubsec.yaml

### ISSUE THREAD

**Issue by Borahb** [infiniteoverflow/Libro#75]
hive_flutter 1.0.0 requires SDK version >=2.12.0 <3.0.0 and no versions of hive_flutter match >1.0.0 <2.0.0, hive_flutter ^1.0.0 is forbidden.
![Screenshot (458)](https://user-images.githubusercontent.com/49881148/111576918-678dd980-87d7-11eb-844e-e3b23a50ca18.png)

Can I solve it?
#gssoc21

**Comment by infiniteoverflow** [comment]
I am sorry @Borahb , this just requires changing 2.7.0 to 2.12 , which cant be considered as a moral PR...

Anyhow , appreciate you raising this issue. Feel free to work on any existing issue or raise any bugs or ui changes you would like to work on.

And if you would like to run the app , just change the versions in your PC and run the app.
