### ISSUE TITLE
Add home_screen & email_verfication_screen imports in the Login_screen.dart   [BUG]

### ISSUE THREAD

**Issue by rohats871** [infiniteoverflow/Libro#89]
**Describe the bug**
without the imports for home screen and email_verfication_screen it gives an build error for iOS devices which can be fixed by just adding them in the Login_screen.dart file.

**To Reproduce**
1. Go to 'Login_screen.dart'
2. on top add the imports
3. Save & run

**Smartphone:**
 - Device: [e.g. iPhone8 to 12]

**Comment by SapinderSingh** [comment]
I can work on this issue. Please assign it to me under GSSOC 21

**Comment by infiniteoverflow** [comment]
@rohank2502 This was an issue with missing imports , it has been fixed , thank you.
