### ISSUE TITLE
Wrapping the text when it is too long 

### ISSUE THREAD

**Issue by EAsmithaShrree** [infiniteoverflow/Libro#91]
When the name of the book or the author is unexpectedly too long, it is taking all the space that is available. However, I feel that all the information must look at least a little uniform. 

Hence, I propose that we either add the ellipsis or the fade feature when the name is too long. Or, another option would be to just let it extend vertically instead of letting it take up horizontal space. 

![image](https://user-images.githubusercontent.com/74728570/112726015-2ae18100-8f41-11eb-9a37-0d71b60efde6.png)

**Comment by SapinderSingh** [comment]
I can work on this issue under GSSOC 21. Please assign it to me.

**Comment by EAsmithaShrree** [comment]
@infiniteoverflow since I opened the issue, I was hoping that it will be assigned to me if you decide that we must work on this issue.

**Comment by EAsmithaShrree** [comment]
@infiniteoverflow May I work on this?

**Comment by infiniteoverflow** [comment]
Sorry for the late reply @EAsmithaShrree  , yes you can start with this.

**Comment by infiniteoverflow** [comment]
You can use TextOverflow attribute of the Text Widget for the same.
