### ISSUE TITLE
Migrating the app to Null Safety

### ISSUE THREAD

**Issue by pawan2806** [infiniteoverflow/Libro#93]
**Is your feature request related to a problem? Please describe.**
With null safety, you can reason about your code with more confidence. No more pesky runtime null dereferencing errors in deployed apps. Instead, you get static errors as you code. ~ dart officials

**Describe the solution you'd like**
Migrate the app to Null Safety

**Describe alternatives you've considered**

**Additional context**

#gssoc21_participant

**Comment by infiniteoverflow** [comment]
Sorry for the late reply @pawan2806  , as of now we are not planning on migrating to null-safety as new comers might face issues with the new syntax. Eventually by the end of the season we will migrate it all together.
