### ISSUE TITLE
Modifying and Styling Readme.md file 

### ISSUE THREAD

**Issue by DOOMSTERR** [infiniteoverflow/Libro#94]
## Request ✨
Hello sir, I want to modify the readme.md file.

### Modifying it by adding 

1.)Adding shield batches in different colors for(at center-top):
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars

2.) Sections
->Feature Section
->In Contributor Section adding
>Project Manager/Admin Section

-> I'll also be adding emojis to make it look more attractive and beautiful.

@infiniteoverflow sir, please allow me to do so, by assigning me the issue under the GSSOC21 label & level label.

Thank you.

**Comment by infiniteoverflow** [comment]
Sure go ahead @DOOMSTERR
