### ISSUE TITLE
Add a "Loading snackbar" during SignUp

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#95]
In the signup screen, when a user clicks "Sign-up", nothing is shown until the firebase auth registers the user successfully and gives a callback.

So we need to integrate a snackbar saying "Creating your account..." with a loader at the end. The same has been integrated for Login , u can use the same.

**Comment by nicks101** [comment]
can I work on it?

**Comment by infiniteoverflow** [comment]
sure go ahead @nicks101
