### ISSUE TITLE
Modify Verification screen

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#96]
<img width="380" alt="Screenshot 2021-04-04 at 9 49 09 AM" src="https://user-images.githubusercontent.com/40236624/113498548-83111800-952b-11eb-8e43-ab671eaac810.png">

We need to add some padding at the bottom, such that the button doesn't get stuck at the bottom.

**Comment by Neha62-lit** [comment]
@infiniteoverflow I would like to work on this issue!!

**Comment by infiniteoverflow** [comment]
Sure , you can go ahead.
