### ISSUE TITLE
Modify the "Verified" dialog

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#97]
<img width="397" alt="Screenshot 2021-04-04 at 9 49 39 AM" src="https://user-images.githubusercontent.com/40236624/113498594-fb77d900-952b-11eb-8c20-006a62742377.png">

The current ui design looks a bit odd, let's try some better designs for the same. Feel free to use any good package u find in pub.dev

**Comment by Samdid** [comment]
@infiniteoverflow I would like to work on this please assign it to me. Also, I am a GSSOC participant

**Comment by infiniteoverflow** [comment]
Sure , go ahead.

**Comment by infiniteoverflow** [comment]
@Samdid update on this ?

**Comment by Ronak8602** [comment]
If there's no response till now from @Samdid can I work on this issue . I know a better flutter package which I can match with the application default UI @infiniteoverflow

**Comment by infiniteoverflow** [comment]
@Ronak8602 , u can get started with this.

**Comment by Ronak8602** [comment]
I have created a alert dialog using giphy package
![Screenshot_2021-04-23-22-13-52-213_com example book_donation](https://user-images.githubusercontent.com/54980955/115903734-8e4bc980-a481-11eb-84b4-a7a9b92e1afb.jpg)
The verify tick image is an giphy which zoom in's and zoom out's
If perfect that I can create a PR @infiniteoverflow

**Comment by Ronak8602** [comment]
Hey @infiniteoverflow  should I make more modifications

**Comment by infiniteoverflow** [comment]
Go ahead @Ronak8602 , make a PR
